### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by Z4R10N** [mclmza/linkedin-learning-downloader#103]
018-07-30 08:13:06,825 - INFO - Authentication successfully completed
Traceback (most recent call last):
  File "C:\sytex\SYSTEM 2 FILES\Desktop\linkedin-learning-downloader-master\lld.py", line 187, in <module>
    main()
  File "C:\sytex\SYSTEM 2 FILES\Desktop\linkedin-learning-downloader-master\lld.py", line 183, in main
    lld.download_courses()
  File "C:\sytex\SYSTEM 2 FILES\Desktop\linkedin-learning-downloader-master\lld.py", line 125, in download_courses
    course_data = resp.json()['elements'][0]
KeyError: 'elements'

**Comment by mclmza** [comment]
Check that the slug is correct.
