### ISSUE TITLE
KeyError: 'transcript'

### ISSUE THREAD

**Issue by sdi22** [mclmza/linkedin-learning-downloader#106]
you can delete this.

**Comment by sdi22** [comment]
Ciao M.,

'installing-and-setting-up-gns3' gives the same error:

`Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 119, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 131, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "linkedin_learning.py", line 166, in fetch_video
    subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']
KeyError: 'transcript'
`
Can you please have a look into this? Grazie mille :)
