### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by lyr0x** [mclmza/linkedin-learning-downloader#2]
II get this Error:

Traceback (most recent call last):
  File "C:\Users\lbt\Tools\linkedin-learning-downloader-master\lld.py", line 94, in <module>
    print '[*] Parsing "%s" course\'s chapters' % course_name
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 38: character maps to <undefined>

How can I solve this?

**Comment by mclmza** [comment]
@lyr0x  what course are you trying to download?
