### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' 

### ISSUE THREAD

**Issue by vincentSTO** [mclmza/linkedin-learning-downloader#24]
Had another issue (after the UTF-8 patch) with course `dynamics-365-for-sales-teams`.

```
[*] Parsing "Dynamics 365 for Sales Teams" course's chapters
[*] [6 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [2 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What you should know"
[*] --- Parsing "1  Enter Customer Data" chapters's videos
[*] --- [6 videos found]
[*] ------ Downloading video "Create a new account"
[*] ------ Downloading video "Create contacts"
Traceback (most recent call last):
  File "lld.py", line 119, in <module>
    (str(vc), video_name))
  File "lld.py", line 77, in download_file
    with open(file_path + '/' + file_name, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 65: ordinal not in range(128)
```

I've resolved it by replacing no-break space for the `video_name`, `chapter_name` and `course_name` variables with normal spaces.

```
video_name = video_name.replace(u'\xa0', u' ') # Replace no-break space with normal space

**Comment by vincentSTO** [comment]
Similar issue for `writing-customer-service-emails`:

```
[*] Parsing "Writing Customer Service Emails" course's chapters
[*] [7 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What is a great customer service email"
[*] ------ Downloading video "Excercise files"
[*] --- Parsing "1  Answer the Customer s Question" chapters's videos
[*] --- [6 videos found]
[*] ------ Downloading video "Learn to read emails critically"
[*] ------ Downloading video "Anticipate follow-up questions"
[*] ------ Downloading video "Answer all of the customer s questions"
[*] ------ Downloading video "How to answer difficult questions"
[*] ------ Downloading video "Challenge  Questions"
[*] ------ Downloading video "Solution  Questions"
[*] --- Parsing "2  Show Customers You ve Read Their Email" chapters's videos
[*] --- [5 videos found]
[*] ------ Downloading video "Explain your process to the customer"
[*] ------ Downloading video "Paraphrase the customer s situation"
[*] ------ Downloading video "Acknowledge the customer s feelings"
[*] ------ Downloading video "Challenge  Reading carefully"
[*] ------ Downloading video "Solution  Reading carefully"
[*] --- Parsing "3  If You Must Apologize  Be Sincere" chapters's videos
[*] --- [6 videos found]
[*] ------ Downloading video "When and how to apologize"
[*] ------ Downloading video "What to write after you apologize"
Traceback (most recent call last):
  File "lld.py", line 120, in <module>
    print '[*] ------ Downloading video "%s"' % video_name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 41: ordinal not in range(128)

```

**Comment by mclmza** [comment]
Does the last commit fix the issue?

**Comment by williamfgm96** [comment]
Similar issue for `aprende-los-formatos-de-video-digital` is an Spanish course.

`
[*] Parsing "Aprende los formatos de v├¡deo digital" course's chapters
[*] [9 chapters found]
[*] --- Parsing "Introducci├│n" chapters's videos
[*] --- [1 videos found]
[*] ------ Downloading video "Presentaci├│n del curso ÔÇ£Aprende los formatos de v├¡deo digitalÔÇØ"
[*] --- Parsing "Introducci├│n al curso Formatos de v├¡deo digital" chapters's videos
[*] --- [2 videos found]
[*] ------ Downloading video "Objetivos del curso Formatos de v├¡deo digital y p├║blico objetivo"
[*] ------ Downloading video "Archivos base de Formatos de v├¡deo digital"
[*] --- Parsing "Qu├® son los formatos de v├¡deo digital" chapters's videos
[*] --- [7 videos found]
[*] ------ Downloading video "Los tres criterios que definen un formato"
[*] ------ Downloading video "Tama├▒o del v├¡deo"
[*] ------ Downloading video "Frame rate"
[*] ------ Downloading video "Aspecto del p├¡xel"
[*] ------ Downloading video "El PAR en el software"
[*] ------ Downloading video "Aspecto de imagen  panoramizaciones"
[*] ------ Downloading video "RGB y 601 709"
[*] --- Parsing "Formatos SD" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "PAL"
`

**Comment by williamfgm96** [comment]
I resolved the issue replacing all `utf-8` for `cp1250`
