### ISSUE TITLE
File "lld.py", line 76, in download_file with open(file_path + '/' + file_name, 'wb') as f:

### ISSUE THREAD

**Issue by milkshoes** [mclmza/linkedin-learning-downloader#5]
Might be related to special characters being written back to the file system? Perhaps related to the 're.sub...' function not being completely accurate?

This occurs for me on Windows 10 every time with certain courses. One of which specifically is the 'remixing-techniques-time-stretching' course.

**Printed Console Output:**

```
[*] Parsing "Remixing Techniques Time Stretching" course's chapters
[*] [8 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What you should know before watching this course"
[*] ------ Downloading video "Why did we record this course in four different digital audio workstations (DAWs)"
[*] ------ Downloading video "Using the exercise files"
[*] --- Parsing "1. Time-Stretching Basics" chapters's videos
[*] --- [2 videos found]
[*] ------ Downloading video "What is time stretchingexpanding"
[*] ------ Downloading video "Exploring different time-stretching scenarios in remixing"
[*] --- Parsing "2. Tools of the Trade" chapters's videos
[*] --- [8 videos found]
[*] ------ Downloading video "Understanding where to get a capella vocal tracks"
[*] ------ Downloading video "Time stretching in Pro Tools"
[*] ------ Downloading video "Time stretching in Logic Pro"
[*] ------ Downloading video "Time stretching in Reason"
[*] ------ Downloading video "Time stretching in Ableton Live"
[*] ------ Downloading video "Understanding the roles of multiple DAWs in a time-stretching workflow"
[*] ------ Downloading video "Dealing with wet vocal stems"
[*] ------ Downloading video "Choosing the tempo for different styles or genres"
[*] --- Parsing "3. Technique 1 Speeding Up Vocals" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Importing vocals and using the 10% time-stretch rule"
[*] ------ Downloading video "Comparing several vocal time stretches at faster BPMs"
[*] ------ Downloading video "Putting the time-stretched vocal in context"
[*] --- Parsing "4. Technique 2 Slowing Down and Double Timing Vocals " chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Setting up your session for double timing a vocal"
Traceback (most recent call last):
  File "lld.py", line 117, in <module>
    (str(vc), video_name))
  File "lld.py", line 76, in download_file
    with open(file_path + '/' + file_name, 'wb') as f:
IOError: [Errno 2] No such file or directory: u'out/Remixing Techniques Time Stretching/4. Technique 2 Slowing Down and Double Timing Vocals /1. Setting up your session for double timing a vocal.mp4'
```

**Comment by milkshoes** [comment]
This different regex pattern and usage as a variable for easier modifications seemed to work a little better for the time-being although there still seems to be an issue on one course for me so far - 'remixing-techniques-time-stretching'

```
invalid_file_chars = r'[^A-Za-z0-9 ]+'
course_name = re.sub(invalid_file_chars, "", course_name)
chapter_name = re.sub(invalid_file_chars, "", chapter['title'])
video_name = re.sub(invalid_file_chars, "", video['title'])
```

**Comment by mclmza** [comment]
@milkshoes first of all thank you for your work.
I did not saw any pull request, send it and it will be accept.

**Comment by milkshoes** [comment]
I tried committing a pull request but it returns the following error:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:master
remote: Permission to mclmza/linkedin-learning-downloader.git denied to milkshoes.
fatal: unable to access 'https://github.com/mclmza/linkedin-learning-downloader.git/': The requested URL returned error: 403

Pushing to https://github.com/mclmza/linkedin-learning-downloader.git
Completed with errors, see above.

Perhaps you need to enable this from a setting?

**Comment by milkshoes** [comment]
Ok, pull request submitted to ya.
