### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014' in position 52: character maps to <undefined>

### ISSUE THREAD

**Issue by milkshoes** [mclmza/linkedin-learning-downloader#6]
Possibly an invalid character "—" in the chapter title: 
'7. Working with Sampler and Simpler—Creative Sampling'

Windows 10, Course = 'ableton-live-producing-electronic-music'

**Printed Console Output:**

```
[*] Parsing "Ableton Live Producing Electronic Music" course's chapters
[*] [13 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What you should know before watching this course"
[*] ------ Downloading video "Using the exercise files"
[*] --- Parsing "1. Getting Started" chapters's videos
[*] --- [6 videos found]
[*] ------ Downloading video "Configuring preferences"
[*] ------ Downloading video "Quick review of Ableton Live basics"
[*] ------ Downloading video "Working with Ableton Live's browser"
[*] ------ Downloading video "The foundation of a track Electronic music production concepts"
[*] ------ Downloading video "Session view and Arrangement view"
[*] ------ Downloading video "Exporting and saving your project"
[*] --- Parsing "2. Working with Audio and MIDI Clips" chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Editing audio and MIDI clips"
[*] ------ Downloading video "Warping basics"
[*] ------ Downloading video "Sends and returns"
[*] ------ Downloading video "Insert effects"
[*] --- Parsing "3. Drum Programming" chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Quick history of traditional drum machines"
[*] ------ Downloading video "Programming drums with Ableton Live's drum racks"
[*] ------ Downloading video "Programming drums, slicing an audio sample, and slicing to MIDI"
[*] ------ Downloading video "Creating custom drum racks for your samples"
[*] --- Parsing "4. Creating Wobble Bass Lines with Analog and Operator" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Creating wobble bass lines with Analog"
[*] ------ Downloading video "Creating call and response bass lines"
[*] ------ Downloading video "Creating wobble bass lines with Operator"
[*] --- Parsing "5. Creating Lead and Pads with Instrument Racks" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Programming leads with instrument racks"
[*] ------ Downloading video "Programming pads and mapping macros"
[*] ------ Downloading video "Chord shapes with Ableton Push"
[*] --- Parsing "6. Advanced MIDI Production Techniques" chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Slice to MIDI"
[*] ------ Downloading video "Harmony to MIDI"
[*] ------ Downloading video "Melody to MIDI"
[*] ------ Downloading video "Drums to MIDI"
Traceback (most recent call last):
  File "lld.py", line 100, in <module>
    print '[*] --- Parsing "%s" chapters\'s videos' % chapter_name
  File "C:\Python\2.7\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014' in position 52: character maps to <undefined>
```

**Comment by milkshoes** [comment]
This different regex pattern and usage as a variable for easier modifications seemed to work a little better for the time-being although there still seems to be an issue on one course for me so far - 'remixing-techniques-time-stretching'

```
invalid_file_chars = r'[^A-Za-z0-9 ]+'
course_name = re.sub(invalid_file_chars, "", course_name)
chapter_name = re.sub(invalid_file_chars, "", chapter['title'])
video_name = re.sub(invalid_file_chars, "", video['title'])
```
