### ISSUE TITLE
problem with @?

### ISSUE THREAD

**Issue by nmassi** [mclmza/linkedin-learning-downloader#69]
```
Traceback (most recent call last):
  File "lld.py", line 7, in <module>
    import config
  File "/Users/me/Desktop/linkedin-learning-downloader/config.py", line 3
SyntaxError: Non-ASCII character '\xe2' in file /Users/me/Desktop/linkedin-learning-downloader/config.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by mclmza** [comment]
Can you link the course?

**Comment by inoutux** [comment]
Try to upgrade python version and modules :)

**Comment by mclmza** [comment]
No answers from the issue author.
