### ISSUE TITLE
I am facing a " KeyError: 'elements' " issue

### ISSUE THREAD

**Issue by coder-apex** [mclmza/linkedin-learning-downloader#86]
My credentials have been successfully authenticated. I am getting the following output:
```
2018-06-29 14:56:44,703 - INFO - Authenticating to LinkedIn
2018-06-29 14:56:44,713 - INFO - Starting new HTTPS connection (1): www.linkedin.com
2018-06-29 14:56:45,105 - INFO - Csfr token: 8ae177bb-96be-424b-8a8d-78c4e2a68240
2018-06-29 14:56:46,417 - INFO - Authentication successfully completed
Traceback (most recent call last):
  File "lld.py", line 187, in <module>
    main()
  File "lld.py", line 183, in main
    lld.download_courses()
  File "lld.py", line 125, in download_courses
    course_data = resp.json()['elements'][0]
KeyError: 'elements'
```
My download location has been set to:
`BASE_DOWNLOAD_PATH = '/home/coder-apex/Documents/Scripts'`

Any help in regard to this will be very helpful. Thank you very much.

**Comment by surajasawa** [comment]
the problem is you have copied wrong course name,
share your config.
will let you know

**Comment by dipayan83** [comment]
i am also facing same issue. check my config file except login.
BASE_DOWNLOAD_PATH = 'D:\linkedin_learning\Courses' #use "/" as separators
SUBS = True
COURSES = 'https://www.linkedin.com/learning/python-data-analysis'

**Comment by basilbaby81** [comment]
In course name use only url slug
 In this case use 'python-data-analysis'

**Comment by mclmza** [comment]
No answers from the issue author.
