### ISSUE TITLE
Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590

### ISSUE THREAD

**Issue by inoutux** [mclmza/linkedin-learning-downloader#93]
Hi @mclmza #! Nice work whit this tool

But now, I have this alert when I run  `python lld.py` 

![screen shot 2018-07-16 at 11 50 53](https://user-images.githubusercontent.com/8160846/42765094-9e00bcee-88ed-11e8-8f0b-b42fe58605c9.png)

Please help me :)

Thanks!

**Comment by mclmza** [comment]
Can you post your config file?

**Comment by inoutux** [comment]
Hi! Sure...    (***** obviusly is my user and pass not reveal)

#!/usr/bin/python

USERNAME = '***********'
PASSWORD = '**********'
BASE_DOWNLOAD_PATH = '' #use "/" as separators
SUBS = True
COURSES = [
    'learning-backbone-js'
]


But now I had this error:

Traceback (most recent call last):
  File "lld.py", line 10, in <module>
    import config
  File "/Users/admin/Desktop/linkedin-learning-downloader-master/config.py", line 3
SyntaxError: Non-ASCII character '\xe2' in file /Users/admin/Desktop/linkedin-learning-downloader-master/config.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

HELP ME :)

Thank you!

**Comment by kumar470** [comment]
same issue as the first comment. just entereed user name password in the config file, no other changes but getting the errors as shown in the first comment

**Comment by mauriziovitale** [comment]
I had the same problem. 

run the command 
**_python -m requests.help_**
you should have something like that
```
"pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }
```
<img width="218" alt="screen shot 2018-07-28 at 19 35 50" src="https://user-images.githubusercontent.com/14923305/43359640-7d43ffde-929d-11e8-86a3-796d99b0c6d1.png">

Run 
```
sudo pip install pyopenssl --user --upgrade

```

This time if you run again 
**_python -m requests.help_**
you should have 
```
"pyOpenSSL": {
    "openssl_version": "1010008f", 
    "version": "18.0.0"
  }, 
```
