### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by tomasL81** [mclmza/linkedin-learning-downloader#94]
Hi, sorry, I know there were already issues opened with this error, but none of them helped me fix it.

error I got is:
C:\Python27>python.exe lld.py
2018-07-16 19:35:32,096 - INFO - Authenticating to LinkedIn
2018-07-16 19:35:35,214 - INFO - Csfr token: c55e8273-fa97-48f0-8ae1-3d2c043e725b
2018-07-16 19:35:36,618 - INFO - Authentication successfully completed
Traceback (most recent call last):
  File "lld.py", line 187, in <module>
    main()
  File "lld.py", line 183, in main
    lld.download_courses()
  File "lld.py", line 125, in download_courses
    course_data = resp.json()['elements'][0]
KeyError: 'elements'

cfg file I got is:
#!/usr/bin/python

USERNAME = '****************'
PASSWORD = '****************'
BASE_DOWNLOAD_PATH = 'd:/linkedin' #use "/" as separators
SUBS = True
COURSES = [
    'azure-ad-connect-health'
]

course name I tried is 'azure-ad-connect-health' as well as 'Azure AD Connect Health'

**Comment by tomasL81** [comment]
nevermind, I got it now.
